create table if not exists matrix_accounts (
    id bigint generated by default as identity primary key,
    account_key text not null unique,
    display_name text not null,
    niche text not null default '',
    status text not null default 'active',
    notes text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists account_platforms (
    id bigint generated by default as identity primary key,
    account_id bigint not null references matrix_accounts(id) on delete cascade,
    platform text not null,
    handle text not null default '',
    enabled integer not null default 1,
    capability_status text not null default 'registered',
    login_status text not null default 'unknown',
    last_checked_at bigint,
    created_at bigint not null,
    updated_at bigint not null,
    unique(account_id, platform)
);

create table if not exists browser_profiles (
    id bigint generated by default as identity primary key,
    account_id bigint not null unique references matrix_accounts(id) on delete cascade,
    profile_dir text not null,
    debug_port integer not null unique,
    fingerprint_json jsonb not null default '{}'::jsonb,
    created_at bigint not null,
    updated_at bigint not null
);

alter table browser_profiles add column if not exists account_id bigint;
alter table browser_profiles add column if not exists fingerprint_json jsonb not null default '{}'::jsonb;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'browser_profiles'
          and column_name = 'account_platform_id'
    ) then
        execute '
            update browser_profiles bp
            set account_id = ap.account_id
            from account_platforms ap
            where bp.account_id is null
              and bp.account_platform_id = ap.id
        ';
    end if;
end $$;

with ranked_browser_profiles as (
    select id, row_number() over (partition by account_id order by updated_at desc, id asc) as rn
    from browser_profiles
    where account_id is not null
)
update browser_profiles bp
set account_id = null
from ranked_browser_profiles ranked
where bp.id = ranked.id
  and ranked.rn > 1;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'browser_profiles'::regclass
          and conname = 'browser_profiles_account_id_fkey'
    ) then
        alter table browser_profiles
        add constraint browser_profiles_account_id_fkey
        foreign key (account_id) references matrix_accounts(id) on delete cascade not valid;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = 'browser_profiles'::regclass
          and conname = 'browser_profiles_account_id_key'
    ) then
        alter table browser_profiles
        add constraint browser_profiles_account_id_key unique (account_id);
    end if;
end $$;

create table if not exists notification_routes (
    id bigint generated by default as identity primary key,
    event_type text not null,
    platform text not null,
    enabled integer not null default 0,
    created_at bigint not null,
    updated_at bigint not null,
    unique(event_type, platform)
);

create table if not exists notification_policies (
    id bigint generated by default as identity primary key,
    event_type text not null,
    severity text not null default '',
    platform text not null default '',
    account_scope text not null default '',
    enabled integer not null default 1,
    target_platforms_json jsonb not null default '[]'::jsonb,
    cooldown_seconds integer not null default 600,
    quiet_start text not null default '',
    quiet_end text not null default '',
    escalation_enabled integer not null default 0,
    escalation_minutes integer not null default 0,
    escalation_platforms_json jsonb not null default '[]'::jsonb,
    owner_hint text not null default '',
    created_at bigint not null,
    updated_at bigint not null,
    unique(event_type, severity, platform, account_scope)
);

create table if not exists notification_incidents (
    id bigint generated by default as identity primary key,
    event_type text not null,
    subtype text not null default '',
    dedupe_key text not null,
    severity text not null default 'info',
    status text not null default 'open',
    title text not null default '',
    summary text not null default '',
    account_id bigint references matrix_accounts(id) on delete set null,
    account_key text not null default '',
    platform text not null default '',
    owner_hint text not null default '',
    source_url text not null default '',
    action_url text not null default '',
    occurrence_count integer not null default 1,
    escalation_count integer not null default 0,
    first_seen_at bigint not null,
    last_seen_at bigint not null,
    acknowledged_at bigint,
    resolved_at bigint,
    assigned_to text not null default '',
    last_escalated_at bigint,
    next_escalate_at bigint,
    payload_json jsonb not null default '{}'::jsonb,
    created_at bigint not null,
    updated_at bigint not null,
    unique(event_type, dedupe_key)
);

create table if not exists notification_actions (
    id bigint generated by default as identity primary key,
    incident_id bigint not null references notification_incidents(id) on delete cascade,
    action text not null,
    actor text not null default '',
    note text not null default '',
    payload_json jsonb not null default '{}'::jsonb,
    created_at bigint not null
);

create index if not exists idx_notification_incidents_status on notification_incidents(status, updated_at);
create index if not exists idx_notification_incidents_escalation on notification_incidents(next_escalate_at, status);
create index if not exists idx_notification_actions_incident on notification_actions(incident_id, created_at);

create table if not exists operation_notices (
    id bigint generated by default as identity primary key,
    category text not null,
    category_label text not null default '',
    view text not null default '',
    view_label text not null default '',
    action_code text not null,
    action_label text not null default '',
    source text not null default '',
    status text not null default 'success',
    summary text not null default '',
    params_json jsonb not null default '{}'::jsonb,
    actor_id text not null default '',
    actor_name text not null default '',
    merge_key text not null default '',
    merged_count integer not null default 1,
    first_seen_at bigint not null,
    last_seen_at bigint not null,
    delivery_status text not null default 'pending',
    delivery_targets_json jsonb not null default '[]'::jsonb,
    delivery_result_json jsonb not null default '{}'::jsonb,
    delivered_at bigint,
    created_at bigint not null,
    updated_at bigint not null
);

create index if not exists idx_operation_notices_category on operation_notices(category, created_at);
create index if not exists idx_operation_notices_status on operation_notices(status, updated_at);
create index if not exists idx_operation_notices_merge on operation_notices(merge_key, delivery_status, delivered_at);

create table if not exists login_qr_batches (
    id bigint generated by default as identity primary key,
    batch_id text not null unique,
    event_type text not null default 'wechat_login_qr',
    status text not null default 'pending',
    payload_json jsonb not null default '{}'::jsonb,
    notified_at bigint,
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists login_qr_items (
    id bigint generated by default as identity primary key,
    batch_id text not null references login_qr_batches(batch_id) on delete cascade,
    account_id bigint not null references matrix_accounts(id) on delete cascade,
    account_key text not null,
    display_name text not null,
    platform text not null default 'wechat',
    profile_dir text not null,
    debug_port integer not null,
    reason text not null default '',
    url text not null default '',
    qr_path text not null default '',
    qr_fingerprint text not null default '',
    status text not null default 'pending',
    created_at bigint not null,
    updated_at bigint not null,
    unique(account_id, platform, qr_fingerprint)
);

create table if not exists automation_tasks (
    id bigint generated by default as identity primary key,
    account_id bigint references matrix_accounts(id) on delete set null,
    platform text not null default '',
    task_type text not null,
    payload_json jsonb not null default '{}'::jsonb,
    status text not null default 'pending',
    summary text not null default '',
    error text not null default '',
    retry_count integer not null default 0,
    last_attempt_at bigint,
    sent_at bigint,
    created_at bigint not null,
    updated_at bigint not null
);

alter table ai_robot_messages add column if not exists retry_count integer not null default 0;
alter table ai_robot_messages add column if not exists last_attempt_at bigint;
alter table ai_robot_messages add column if not exists sent_at bigint;

create table if not exists video_stats_snapshots (
    id bigint generated by default as identity primary key,
    account_id bigint references matrix_accounts(id) on delete set null,
    platform text not null,
    video_ref text not null default '',
    stat_date text not null default '',
    title text not null default '',
    feed_id text not null default '',
    views bigint not null default 0,
    likes bigint not null default 0,
    comments bigint not null default 0,
    shares bigint not null default 0,
    messages bigint not null default 0,
    published_at text not null default '',
    source text not null default '',
    raw_json jsonb not null default '{}'::jsonb,
    captured_at bigint not null
);

alter table video_stats_snapshots add column if not exists stat_date text not null default '';
alter table video_stats_snapshots add column if not exists title text not null default '';
alter table video_stats_snapshots add column if not exists feed_id text not null default '';
alter table video_stats_snapshots add column if not exists source text not null default '';
alter table video_stats_snapshots add column if not exists raw_json jsonb not null default '{}'::jsonb;

create table if not exists wechat_stats_account_snapshots (
    id bigint generated by default as identity primary key,
    account_id bigint not null references matrix_accounts(id) on delete cascade,
    platform text not null default 'wechat',
    stat_date text not null,
    views bigint not null default 0,
    likes bigint not null default 0,
    comments bigint not null default 0,
    shares bigint not null default 0,
    messages bigint not null default 0,
    followers bigint not null default 0,
    follower_delta bigint not null default 0,
    profile_visits bigint not null default 0,
    leads bigint not null default 0,
    completed_rate numeric not null default 0,
    interaction_rate numeric not null default 0,
    works_count bigint not null default 0,
    source text not null default 'wechat_stats_capture',
    raw_json jsonb not null default '{}'::jsonb,
    captured_at bigint not null,
    created_at bigint not null,
    updated_at bigint not null,
    unique(account_id, platform, stat_date)
);

create table if not exists wechat_stats_capture_runs (
    id bigint generated by default as identity primary key,
    run_id text not null unique,
    target_date text not null,
    status text not null default 'running',
    batch_size integer not null default 5,
    limit_accounts integer not null default 0,
    dry_run integer not null default 0,
    account_total integer not null default 0,
    captured_accounts integer not null default 0,
    skipped_accounts integer not null default 0,
    failed_accounts integer not null default 0,
    payload_json jsonb not null default '{}'::jsonb,
    error text not null default '',
    started_at bigint not null,
    finished_at bigint,
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists ai_robot_configs (
    id bigint generated by default as identity primary key,
    platform text not null unique,
    enabled integer not null default 0,
    bot_name text not null default '',
    webhook_url text not null default '',
    webhook_secret text not null default '',
    signing_secret text not null default '',
    target_id text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists ai_robot_messages (
    id bigint generated by default as identity primary key,
    platform text not null,
    message_type text not null default 'text',
    payload_json jsonb not null default '{}'::jsonb,
    status text not null default 'pending',
    summary text not null default '',
    error text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists brand_settings (
    id integer primary key check (id = 1),
    name text not null default 'GasGx',
    slogan text not null default 'Video Distribution',
    logo_asset_path text not null default '',
    primary_color text not null default '#5dd62c',
    theme_id text not null default 'gasgx-green',
    default_account_prefix text not null default 'GasGx',
    created_at bigint not null,
    updated_at bigint not null
);

alter table brand_settings add column if not exists logo_asset_path text not null default '';
alter table brand_settings add column if not exists primary_color text not null default '#5dd62c';
alter table brand_settings add column if not exists theme_id text not null default 'gasgx-green';
alter table brand_settings add column if not exists default_account_prefix text not null default 'GasGx';

create table if not exists schema_migrations (
    version text primary key,
    app_version text not null default '',
    applied_at bigint not null
);

create table if not exists app_settings (
    id bigint generated by default as identity primary key,
    setting_key text not null unique,
    payload_json jsonb not null default '{}'::jsonb,
    updated_at bigint not null
);

create table if not exists analytics_items (
    id bigint generated by default as identity primary key,
    section text not null,
    item_key text not null,
    payload_json jsonb not null default '{}'::jsonb,
    source text not null default 'seed',
    sort_order integer not null default 0,
    created_at bigint not null,
    updated_at bigint not null,
    unique(section, item_key)
);

create table if not exists video_matrix_assets (
    id bigint generated by default as identity primary key,
    asset_key text not null unique,
    asset_type text not null,
    title text not null default '',
    path text not null default '',
    status text not null default 'available',
    metadata_json jsonb not null default '{}'::jsonb,
    source text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists video_matrix_jobs (
    id bigint generated by default as identity primary key,
    job_key text not null unique,
    status text not null default 'queued',
    stage text not null default '',
    progress numeric not null default 0,
    message text not null default '',
    request_json jsonb not null default '{}'::jsonb,
    assets_json jsonb not null default '[]'::jsonb,
    error text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists video_matrix_generation_runs (
    id bigint generated by default as identity primary key,
    job_key text not null,
    bgm_filename text not null default '',
    bgm_path text not null default '',
    request_json jsonb not null default '{}'::jsonb,
    composition_json jsonb not null default '[]'::jsonb,
    created_at bigint not null
);

create table if not exists video_matrix_generation_assets (
    id bigint generated by default as identity primary key,
    run_id bigint references video_matrix_generation_runs(id) on delete cascade,
    job_key text not null,
    sequence_number integer not null default 0,
    signature text not null default '',
    title text not null default '',
    slogan text not null default '',
    video_path text not null default '',
    cover_path text not null default '',
    copy_path text not null default '',
    manifest_path text not null default '',
    template_id text not null default '',
    cover_template_id text not null default '',
    copy_language text not null default '',
    metadata_json jsonb not null default '{}'::jsonb,
    created_at bigint not null
);

create table if not exists video_matrix_generation_segments (
    id bigint generated by default as identity primary key,
    run_id bigint references video_matrix_generation_runs(id) on delete cascade,
    asset_id bigint references video_matrix_generation_assets(id) on delete cascade,
    job_key text not null,
    sequence_number integer not null default 0,
    segment_index integer not null default 0,
    clip_id text not null default '',
    category text not null default '',
    source_path text not null default '',
    normalized_path text not null default '',
    start_time numeric not null default 0,
    duration numeric not null default 0,
    created_at bigint not null
);

create table if not exists app_seed_runs (
    seed_version text primary key,
    summary_json jsonb not null default '{}'::jsonb,
    applied_at bigint not null
);

create or replace function dashboard_summary()
returns table (
    accounts bigint,
    platforms bigint,
    running_tasks bigint,
    failed_tasks bigint,
    unsupported_tasks bigint,
    remaining_material_videos bigint,
    views bigint,
    likes bigint,
    comments bigint,
    messages bigint
)
language sql
stable
as $$
    select
        (select count(*) from matrix_accounts) as accounts,
        (select count(*) from account_platforms where enabled = 1) as platforms,
        (select count(*) from automation_tasks where status in ('pending', 'running')) as running_tasks,
        (select count(*) from automation_tasks where status = 'failed') as failed_tasks,
        (select count(*) from automation_tasks where status = 'unsupported') as unsupported_tasks,
        0::bigint as remaining_material_videos,
        coalesce((select sum(views) from wechat_stats_account_snapshots where stat_date = (select max(stat_date) from wechat_stats_account_snapshots)), (select sum(views) from video_stats_snapshots), 0)::bigint as views,
        coalesce((select sum(likes) from wechat_stats_account_snapshots where stat_date = (select max(stat_date) from wechat_stats_account_snapshots)), (select sum(likes) from video_stats_snapshots), 0)::bigint as likes,
        coalesce((select sum(comments) from wechat_stats_account_snapshots where stat_date = (select max(stat_date) from wechat_stats_account_snapshots)), (select sum(comments) from video_stats_snapshots), 0)::bigint as comments,
        coalesce((select sum(messages) from wechat_stats_account_snapshots where stat_date = (select max(stat_date) from wechat_stats_account_snapshots)), (select sum(messages) from video_stats_snapshots), 0)::bigint as messages
$$;

create table if not exists brand_members (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null check (role in ('owner', 'admin', 'operator', 'viewer')),
    created_at bigint not null,
    updated_at bigint not null
);

create or replace function brand_current_role()
returns text
language sql
security definer
set search_path = public
stable
as $$
    select role from brand_members where user_id = auth.uid()
$$;

create or replace function brand_has_role(allowed_roles text[])
returns boolean
language sql
security definer
set search_path = public
stable
as $$
    select coalesce(brand_current_role() = any(allowed_roles), false)
$$;

alter table matrix_accounts enable row level security;
alter table account_platforms enable row level security;
alter table browser_profiles enable row level security;
alter table notification_routes enable row level security;
alter table notification_policies enable row level security;
alter table notification_incidents enable row level security;
alter table notification_actions enable row level security;
alter table operation_notices enable row level security;
alter table login_qr_batches enable row level security;
alter table login_qr_items enable row level security;
alter table automation_tasks enable row level security;
alter table video_stats_snapshots enable row level security;
alter table wechat_stats_account_snapshots enable row level security;
alter table wechat_stats_capture_runs enable row level security;
alter table ai_robot_configs enable row level security;
alter table ai_robot_messages enable row level security;
alter table brand_settings enable row level security;
alter table schema_migrations enable row level security;
alter table app_settings enable row level security;
alter table analytics_items enable row level security;
alter table video_matrix_assets enable row level security;
alter table video_matrix_jobs enable row level security;
alter table video_matrix_generation_runs enable row level security;
alter table video_matrix_generation_assets enable row level security;
alter table video_matrix_generation_segments enable row level security;
alter table app_seed_runs enable row level security;
alter table brand_members enable row level security;

drop policy if exists "brand members can read own row" on brand_members;
create policy "brand members can read own row"
on brand_members for select
to authenticated
using (user_id = auth.uid() or brand_has_role(array['owner', 'admin']));

drop policy if exists "brand owners manage members" on brand_members;
create policy "brand owners manage members"
on brand_members for all
to authenticated
using (brand_has_role(array['owner']))
with check (brand_has_role(array['owner']));

drop policy if exists "brand viewers read accounts" on matrix_accounts;
create policy "brand viewers read accounts"
on matrix_accounts for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage accounts" on matrix_accounts;
create policy "brand operators manage accounts"
on matrix_accounts for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read account platforms" on account_platforms;
create policy "brand viewers read account platforms"
on account_platforms for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage account platforms" on account_platforms;
create policy "brand operators manage account platforms"
on account_platforms for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read browser profiles" on browser_profiles;
create policy "brand viewers read browser profiles"
on browser_profiles for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage browser profiles" on browser_profiles;
create policy "brand operators manage browser profiles"
on browser_profiles for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read tasks" on automation_tasks;
create policy "brand viewers read tasks"
on automation_tasks for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage tasks" on automation_tasks;
create policy "brand operators manage tasks"
on automation_tasks for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read stats" on video_stats_snapshots;
create policy "brand viewers read stats"
on video_stats_snapshots for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators import stats" on video_stats_snapshots;
create policy "brand operators import stats"
on video_stats_snapshots for insert
to authenticated
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read account stats" on wechat_stats_account_snapshots;
create policy "brand viewers read account stats"
on wechat_stats_account_snapshots for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage account stats" on wechat_stats_account_snapshots;
create policy "brand operators manage account stats"
on wechat_stats_account_snapshots for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read stats capture runs" on wechat_stats_capture_runs;
create policy "brand viewers read stats capture runs"
on wechat_stats_capture_runs for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage stats capture runs" on wechat_stats_capture_runs;
create policy "brand operators manage stats capture runs"
on wechat_stats_capture_runs for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read notification routes" on notification_routes;
create policy "brand viewers read notification routes"
on notification_routes for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage notification routes" on notification_routes;
create policy "brand operators manage notification routes"
on notification_routes for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read notification policies" on notification_policies;
create policy "brand viewers read notification policies"
on notification_policies for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand admins manage notification policies" on notification_policies;
create policy "brand admins manage notification policies"
on notification_policies for all
to authenticated
using (brand_has_role(array['owner', 'admin']))
with check (brand_has_role(array['owner', 'admin']));

drop policy if exists "brand viewers read notification incidents" on notification_incidents;
create policy "brand viewers read notification incidents"
on notification_incidents for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage notification incidents" on notification_incidents;
create policy "brand operators manage notification incidents"
on notification_incidents for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read notification actions" on notification_actions;
create policy "brand viewers read notification actions"
on notification_actions for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage notification actions" on notification_actions;
create policy "brand operators manage notification actions"
on notification_actions for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read operation notices" on operation_notices;
create policy "brand viewers read operation notices"
on operation_notices for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage operation notices" on operation_notices;
create policy "brand operators manage operation notices"
on operation_notices for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand admins manage robot configs" on ai_robot_configs;
create policy "brand admins manage robot configs"
on ai_robot_configs for all
to authenticated
using (brand_has_role(array['owner', 'admin']))
with check (brand_has_role(array['owner', 'admin']));

drop policy if exists "brand operators read robot configs" on ai_robot_configs;
create policy "brand operators read robot configs"
on ai_robot_configs for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read robot messages" on ai_robot_messages;
create policy "brand viewers read robot messages"
on ai_robot_messages for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage robot messages" on ai_robot_messages;
create policy "brand operators manage robot messages"
on ai_robot_messages for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read settings" on brand_settings;
create policy "brand viewers read settings"
on brand_settings for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand admins manage settings" on brand_settings;
create policy "brand admins manage settings"
on brand_settings for all
to authenticated
using (brand_has_role(array['owner', 'admin']))
with check (brand_has_role(array['owner', 'admin']));

drop policy if exists "brand viewers read migrations" on schema_migrations;
create policy "brand viewers read migrations"
on schema_migrations for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand admins manage migrations" on schema_migrations;
create policy "brand admins manage migrations"
on schema_migrations for all
to authenticated
using (brand_has_role(array['owner', 'admin']))
with check (brand_has_role(array['owner', 'admin']));

drop policy if exists "brand viewers read app settings" on app_settings;
create policy "brand viewers read app settings"
on app_settings for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand admins manage app settings" on app_settings;
create policy "brand admins manage app settings"
on app_settings for all
to authenticated
using (brand_has_role(array['owner', 'admin']))
with check (brand_has_role(array['owner', 'admin']));

drop policy if exists "brand viewers read analytics items" on analytics_items;
create policy "brand viewers read analytics items"
on analytics_items for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage analytics items" on analytics_items;
create policy "brand operators manage analytics items"
on analytics_items for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read video matrix assets" on video_matrix_assets;
create policy "brand viewers read video matrix assets"
on video_matrix_assets for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage video matrix assets" on video_matrix_assets;
create policy "brand operators manage video matrix assets"
on video_matrix_assets for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read video matrix jobs" on video_matrix_jobs;
create policy "brand viewers read video matrix jobs"
on video_matrix_jobs for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage video matrix jobs" on video_matrix_jobs;
create policy "brand operators manage video matrix jobs"
on video_matrix_jobs for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read video matrix generation runs" on video_matrix_generation_runs;
create policy "brand viewers read video matrix generation runs"
on video_matrix_generation_runs for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage video matrix generation runs" on video_matrix_generation_runs;
create policy "brand operators manage video matrix generation runs"
on video_matrix_generation_runs for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read video matrix generation assets" on video_matrix_generation_assets;
create policy "brand viewers read video matrix generation assets"
on video_matrix_generation_assets for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage video matrix generation assets" on video_matrix_generation_assets;
create policy "brand operators manage video matrix generation assets"
on video_matrix_generation_assets for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read video matrix generation segments" on video_matrix_generation_segments;
create policy "brand viewers read video matrix generation segments"
on video_matrix_generation_segments for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage video matrix generation segments" on video_matrix_generation_segments;
create policy "brand operators manage video matrix generation segments"
on video_matrix_generation_segments for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand admins read seed runs" on app_seed_runs;
create policy "brand admins read seed runs"
on app_seed_runs for select
to authenticated
using (brand_has_role(array['owner', 'admin']));

drop policy if exists "brand admins manage seed runs" on app_seed_runs;
create policy "brand admins manage seed runs"
on app_seed_runs for all
to authenticated
using (brand_has_role(array['owner', 'admin']))
with check (brand_has_role(array['owner', 'admin']));

notify pgrst, 'reload schema';
