create table if not exists matrix_accounts (
    id bigint generated by default as identity primary key,
    account_key text not null unique,
    display_name text not null,
    niche text not null default '',
    status text not null default 'active',
    notes text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists account_platforms (
    id bigint generated by default as identity primary key,
    account_id bigint not null references matrix_accounts(id) on delete cascade,
    platform text not null,
    handle text not null default '',
    enabled integer not null default 1,
    capability_status text not null default 'registered',
    login_status text not null default 'unknown',
    last_checked_at bigint,
    created_at bigint not null,
    updated_at bigint not null,
    unique(account_id, platform)
);

create table if not exists browser_profiles (
    id bigint generated by default as identity primary key,
    account_platform_id bigint not null unique references account_platforms(id) on delete cascade,
    profile_dir text not null,
    debug_port integer not null unique,
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists automation_tasks (
    id bigint generated by default as identity primary key,
    account_id bigint references matrix_accounts(id) on delete set null,
    platform text not null default '',
    task_type text not null,
    payload_json jsonb not null default '{}'::jsonb,
    status text not null default 'pending',
    summary text not null default '',
    error text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists video_stats_snapshots (
    id bigint generated by default as identity primary key,
    account_id bigint references matrix_accounts(id) on delete set null,
    platform text not null,
    video_ref text not null default '',
    views bigint not null default 0,
    likes bigint not null default 0,
    comments bigint not null default 0,
    shares bigint not null default 0,
    messages bigint not null default 0,
    published_at text not null default '',
    captured_at bigint not null
);

create table if not exists ai_robot_configs (
    id bigint generated by default as identity primary key,
    platform text not null unique,
    enabled integer not null default 0,
    bot_name text not null default '',
    webhook_url text not null default '',
    webhook_secret text not null default '',
    signing_secret text not null default '',
    target_id text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists ai_robot_messages (
    id bigint generated by default as identity primary key,
    platform text not null,
    message_type text not null default 'text',
    payload_json jsonb not null default '{}'::jsonb,
    status text not null default 'pending',
    summary text not null default '',
    error text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists brand_settings (
    id integer primary key check (id = 1),
    name text not null default 'GasGx',
    slogan text not null default 'Video Distribution',
    logo_asset_path text not null default '',
    primary_color text not null default '#5dd62c',
    theme_id text not null default 'gasgx-green',
    default_account_prefix text not null default 'GasGx',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists schema_migrations (
    version text primary key,
    app_version text not null default '',
    applied_at bigint not null
);

create table if not exists brand_members (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null check (role in ('owner', 'admin', 'operator', 'viewer')),
    created_at bigint not null,
    updated_at bigint not null
);

create or replace function brand_current_role()
returns text
language sql
security definer
set search_path = public
stable
as $$
    select role from brand_members where user_id = auth.uid()
$$;

create or replace function brand_has_role(allowed_roles text[])
returns boolean
language sql
security definer
set search_path = public
stable
as $$
    select coalesce(brand_current_role() = any(allowed_roles), false)
$$;

alter table matrix_accounts enable row level security;
alter table account_platforms enable row level security;
alter table browser_profiles enable row level security;
alter table automation_tasks enable row level security;
alter table video_stats_snapshots enable row level security;
alter table ai_robot_configs enable row level security;
alter table ai_robot_messages enable row level security;
alter table brand_settings enable row level security;
alter table schema_migrations enable row level security;
alter table brand_members enable row level security;

drop policy if exists "brand members can read own row" on brand_members;
create policy "brand members can read own row"
on brand_members for select
to authenticated
using (user_id = auth.uid() or brand_has_role(array['owner', 'admin']));

drop policy if exists "brand owners manage members" on brand_members;
create policy "brand owners manage members"
on brand_members for all
to authenticated
using (brand_has_role(array['owner']))
with check (brand_has_role(array['owner']));

drop policy if exists "brand viewers read accounts" on matrix_accounts;
create policy "brand viewers read accounts"
on matrix_accounts for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage accounts" on matrix_accounts;
create policy "brand operators manage accounts"
on matrix_accounts for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read account platforms" on account_platforms;
create policy "brand viewers read account platforms"
on account_platforms for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage account platforms" on account_platforms;
create policy "brand operators manage account platforms"
on account_platforms for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read browser profiles" on browser_profiles;
create policy "brand viewers read browser profiles"
on browser_profiles for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage browser profiles" on browser_profiles;
create policy "brand operators manage browser profiles"
on browser_profiles for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read tasks" on automation_tasks;
create policy "brand viewers read tasks"
on automation_tasks for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage tasks" on automation_tasks;
create policy "brand operators manage tasks"
on automation_tasks for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read stats" on video_stats_snapshots;
create policy "brand viewers read stats"
on video_stats_snapshots for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators import stats" on video_stats_snapshots;
create policy "brand operators import stats"
on video_stats_snapshots for insert
to authenticated
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand admins manage robot configs" on ai_robot_configs;
create policy "brand admins manage robot configs"
on ai_robot_configs for all
to authenticated
using (brand_has_role(array['owner', 'admin']))
with check (brand_has_role(array['owner', 'admin']));

drop policy if exists "brand operators read robot configs" on ai_robot_configs;
create policy "brand operators read robot configs"
on ai_robot_configs for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read robot messages" on ai_robot_messages;
create policy "brand viewers read robot messages"
on ai_robot_messages for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand operators manage robot messages" on ai_robot_messages;
create policy "brand operators manage robot messages"
on ai_robot_messages for all
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator']))
with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read settings" on brand_settings;
create policy "brand viewers read settings"
on brand_settings for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand admins manage settings" on brand_settings;
create policy "brand admins manage settings"
on brand_settings for all
to authenticated
using (brand_has_role(array['owner', 'admin']))
with check (brand_has_role(array['owner', 'admin']));

drop policy if exists "brand viewers read migrations" on schema_migrations;
create policy "brand viewers read migrations"
on schema_migrations for select
to authenticated
using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));

drop policy if exists "brand admins manage migrations" on schema_migrations;
create policy "brand admins manage migrations"
on schema_migrations for all
to authenticated
using (brand_has_role(array['owner', 'admin']))
with check (brand_has_role(array['owner', 'admin']));
