create table if not exists brand_instances (
    id text primary key,
    name text not null,
    domain text not null unique,
    supabase_url text not null default '',
    service_key_ref text not null default '',
    anon_key text not null default '',
    database_path text not null default '',
    schema_version text not null default '',
    app_version text not null default '',
    status text not null default 'active',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists brand_templates (
    id text primary key,
    name text not null,
    payload_json jsonb not null default '{}'::jsonb,
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists upgrade_runs (
    id bigint generated by default as identity primary key,
    target_schema_version text not null,
    target_app_version text not null,
    status text not null default 'running',
    summary text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists upgrade_run_items (
    id bigint generated by default as identity primary key,
    run_id bigint not null references upgrade_runs(id) on delete cascade,
    brand_id text not null,
    status text not null default 'pending',
    error text not null default '',
    started_at bigint,
    finished_at bigint
);
