create table if not exists matrix_accounts (
    id bigint generated by default as identity primary key,
    account_key text not null unique,
    display_name text not null,
    niche text not null default '',
    status text not null default 'active',
    notes text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists account_platforms (
    id bigint generated by default as identity primary key,
    account_id bigint not null references matrix_accounts(id) on delete cascade,
    platform text not null,
    handle text not null default '',
    enabled integer not null default 1,
    capability_status text not null default 'registered',
    login_status text not null default 'unknown',
    last_checked_at bigint,
    created_at bigint not null,
    updated_at bigint not null,
    unique(account_id, platform)
);

create table if not exists browser_profiles (
    id bigint generated by default as identity primary key,
    account_platform_id bigint not null unique references account_platforms(id) on delete cascade,
    profile_dir text not null,
    debug_port integer not null unique,
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists automation_tasks (
    id bigint generated by default as identity primary key,
    account_id bigint references matrix_accounts(id) on delete set null,
    platform text not null default '',
    task_type text not null,
    payload_json jsonb not null default '{}'::jsonb,
    status text not null default 'pending',
    summary text not null default '',
    error text not null default '',
    retry_count integer not null default 0,
    last_attempt_at bigint,
    sent_at bigint,
    created_at bigint not null,
    updated_at bigint not null
);

alter table ai_robot_messages add column if not exists retry_count integer not null default 0;
alter table ai_robot_messages add column if not exists last_attempt_at bigint;
alter table ai_robot_messages add column if not exists sent_at bigint;

create table if not exists video_stats_snapshots (
    id bigint generated by default as identity primary key,
    account_id bigint references matrix_accounts(id) on delete set null,
    platform text not null,
    video_ref text not null default '',
    views bigint not null default 0,
    likes bigint not null default 0,
    comments bigint not null default 0,
    shares bigint not null default 0,
    messages bigint not null default 0,
    published_at text not null default '',
    captured_at bigint not null
);

create table if not exists ai_robot_configs (
    id bigint generated by default as identity primary key,
    platform text not null unique,
    enabled integer not null default 0,
    bot_name text not null default '',
    webhook_url text not null default '',
    webhook_secret text not null default '',
    signing_secret text not null default '',
    target_id text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists ai_robot_messages (
    id bigint generated by default as identity primary key,
    platform text not null,
    message_type text not null default 'text',
    payload_json jsonb not null default '{}'::jsonb,
    status text not null default 'pending',
    summary text not null default '',
    error text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);
