create table if not exists brand_settings (
    id integer primary key check (id = 1),
    name text not null default 'GasGx',
    slogan text not null default 'Video Distribution',
    logo_asset_path text not null default '',
    primary_color text not null default '#5dd62c',
    theme_id text not null default 'gasgx-green',
    default_account_prefix text not null default 'GasGx',
    created_at bigint not null,
    updated_at bigint not null
);

alter table brand_settings add column if not exists logo_asset_path text not null default '';
alter table brand_settings add column if not exists primary_color text not null default '#5dd62c';
alter table brand_settings add column if not exists theme_id text not null default 'gasgx-green';
alter table brand_settings add column if not exists default_account_prefix text not null default 'GasGx';

create table if not exists schema_migrations (
    version text primary key,
    app_version text not null default '',
    applied_at bigint not null
);

create table if not exists app_settings (
    id bigint generated by default as identity primary key,
    setting_key text not null unique,
    payload_json jsonb not null default '{}'::jsonb,
    updated_at bigint not null
);

create table if not exists analytics_items (
    id bigint generated by default as identity primary key,
    section text not null,
    item_key text not null,
    payload_json jsonb not null default '{}'::jsonb,
    source text not null default 'seed',
    sort_order integer not null default 0,
    created_at bigint not null,
    updated_at bigint not null,
    unique(section, item_key)
);

create table if not exists video_matrix_assets (
    id bigint generated by default as identity primary key,
    asset_key text not null unique,
    asset_type text not null,
    title text not null default '',
    path text not null default '',
    status text not null default 'available',
    metadata_json jsonb not null default '{}'::jsonb,
    source text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists video_matrix_jobs (
    id bigint generated by default as identity primary key,
    job_key text not null unique,
    status text not null default 'queued',
    stage text not null default '',
    progress numeric not null default 0,
    message text not null default '',
    request_json jsonb not null default '{}'::jsonb,
    assets_json jsonb not null default '[]'::jsonb,
    error text not null default '',
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists app_seed_runs (
    seed_version text primary key,
    summary_json jsonb not null default '{}'::jsonb,
    applied_at bigint not null
);
