alter table video_stats_snapshots add column if not exists stat_date text not null default '';
alter table video_stats_snapshots add column if not exists title text not null default '';
alter table video_stats_snapshots add column if not exists feed_id text not null default '';
alter table video_stats_snapshots add column if not exists source text not null default '';
alter table video_stats_snapshots add column if not exists raw_json jsonb not null default '{}'::jsonb;

create table if not exists wechat_stats_account_snapshots (
    id bigint generated by default as identity primary key,
    account_id bigint not null references matrix_accounts(id) on delete cascade,
    platform text not null default 'wechat',
    stat_date text not null,
    views bigint not null default 0,
    likes bigint not null default 0,
    comments bigint not null default 0,
    shares bigint not null default 0,
    messages bigint not null default 0,
    followers bigint not null default 0,
    follower_delta bigint not null default 0,
    profile_visits bigint not null default 0,
    leads bigint not null default 0,
    completed_rate numeric not null default 0,
    interaction_rate numeric not null default 0,
    works_count bigint not null default 0,
    source text not null default 'wechat_stats_capture',
    raw_json jsonb not null default '{}'::jsonb,
    captured_at bigint not null,
    created_at bigint not null,
    updated_at bigint not null,
    unique(account_id, platform, stat_date)
);

create table if not exists wechat_stats_capture_runs (
    id bigint generated by default as identity primary key,
    run_id text not null unique,
    target_date text not null,
    status text not null default 'running',
    batch_size integer not null default 5,
    limit_accounts integer not null default 0,
    dry_run integer not null default 0,
    account_total integer not null default 0,
    captured_accounts integer not null default 0,
    skipped_accounts integer not null default 0,
    failed_accounts integer not null default 0,
    payload_json jsonb not null default '{}'::jsonb,
    error text not null default '',
    started_at bigint not null,
    finished_at bigint,
    created_at bigint not null,
    updated_at bigint not null
);
