create table if not exists notification_routes (
    id bigint generated by default as identity primary key,
    event_type text not null,
    platform text not null,
    enabled integer not null default 0,
    created_at bigint not null,
    updated_at bigint not null,
    unique(event_type, platform)
);
create table if not exists notification_policies (
    id bigint generated by default as identity primary key,
    event_type text not null,
    severity text not null default '',
    platform text not null default '',
    account_scope text not null default '',
    enabled integer not null default 1,
    target_platforms_json jsonb not null default '[]'::jsonb,
    cooldown_seconds integer not null default 600,
    quiet_start text not null default '',
    quiet_end text not null default '',
    escalation_enabled integer not null default 0,
    escalation_minutes integer not null default 0,
    escalation_platforms_json jsonb not null default '[]'::jsonb,
    owner_hint text not null default '',
    created_at bigint not null,
    updated_at bigint not null,
    unique(event_type, severity, platform, account_scope)
);
create table if not exists notification_incidents (
    id bigint generated by default as identity primary key,
    event_type text not null,
    subtype text not null default '',
    dedupe_key text not null,
    severity text not null default 'info',
    status text not null default 'open',
    title text not null default '',
    summary text not null default '',
    account_id bigint references matrix_accounts(id) on delete set null,
    account_key text not null default '',
    platform text not null default '',
    owner_hint text not null default '',
    source_url text not null default '',
    action_url text not null default '',
    occurrence_count integer not null default 1,
    escalation_count integer not null default 0,
    first_seen_at bigint not null,
    last_seen_at bigint not null,
    acknowledged_at bigint,
    resolved_at bigint,
    assigned_to text not null default '',
    last_escalated_at bigint,
    next_escalate_at bigint,
    payload_json jsonb not null default '{}'::jsonb,
    created_at bigint not null,
    updated_at bigint not null,
    unique(event_type, dedupe_key)
);
create table if not exists notification_actions (
    id bigint generated by default as identity primary key,
    incident_id bigint not null references notification_incidents(id) on delete cascade,
    action text not null,
    actor text not null default '',
    note text not null default '',
    payload_json jsonb not null default '{}'::jsonb,
    created_at bigint not null
);
create index if not exists idx_notification_incidents_status on notification_incidents(status, updated_at);
create index if not exists idx_notification_incidents_escalation on notification_incidents(next_escalate_at, status);
create index if not exists idx_notification_actions_incident on notification_actions(incident_id, created_at);
create table if not exists login_qr_batches (
    id bigint generated by default as identity primary key,
    batch_id text not null unique,
    event_type text not null default 'wechat_login_qr',
    status text not null default 'pending',
    payload_json jsonb not null default '{}'::jsonb,
    notified_at bigint,
    created_at bigint not null,
    updated_at bigint not null
);
create table if not exists login_qr_items (
    id bigint generated by default as identity primary key,
    batch_id text not null references login_qr_batches(batch_id) on delete cascade,
    account_id bigint not null references matrix_accounts(id) on delete cascade,
    account_key text not null,
    display_name text not null,
    platform text not null default 'wechat',
    profile_dir text not null,
    debug_port integer not null,
    reason text not null default '',
    url text not null default '',
    qr_path text not null default '',
    qr_fingerprint text not null default '',
    status text not null default 'pending',
    created_at bigint not null,
    updated_at bigint not null,
    unique(account_id, platform, qr_fingerprint)
);
