create table if not exists notification_routes (
    id bigint generated by default as identity primary key,
    event_type text not null,
    platform text not null,
    enabled integer not null default 0,
    created_at bigint not null,
    updated_at bigint not null,
    unique(event_type, platform)
);

create table if not exists login_qr_batches (
    id bigint generated by default as identity primary key,
    batch_id text not null unique,
    event_type text not null default 'wechat_login_qr',
    status text not null default 'pending',
    payload_json jsonb not null default '{}'::jsonb,
    notified_at bigint,
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists login_qr_items (
    id bigint generated by default as identity primary key,
    batch_id text not null references login_qr_batches(batch_id) on delete cascade,
    account_id bigint not null references matrix_accounts(id) on delete cascade,
    account_key text not null,
    display_name text not null,
    platform text not null default 'wechat',
    profile_dir text not null,
    debug_port integer not null,
    reason text not null default '',
    url text not null default '',
    qr_path text not null default '',
    qr_fingerprint text not null default '',
    status text not null default 'pending',
    created_at bigint not null,
    updated_at bigint not null,
    unique(account_id, platform, qr_fingerprint)
);
