create table if not exists video_matrix_generation_runs (
    id bigint generated by default as identity primary key,
    job_key text not null,
    bgm_filename text not null default '',
    bgm_path text not null default '',
    request_json jsonb not null default '{}'::jsonb,
    composition_json jsonb not null default '[]'::jsonb,
    created_at bigint not null
);

create table if not exists video_matrix_generation_assets (
    id bigint generated by default as identity primary key,
    run_id bigint references video_matrix_generation_runs(id) on delete cascade,
    job_key text not null,
    sequence_number integer not null default 0,
    signature text not null default '',
    title text not null default '',
    slogan text not null default '',
    video_path text not null default '',
    cover_path text not null default '',
    copy_path text not null default '',
    manifest_path text not null default '',
    template_id text not null default '',
    cover_template_id text not null default '',
    copy_language text not null default '',
    metadata_json jsonb not null default '{}'::jsonb,
    created_at bigint not null
);

create table if not exists video_matrix_generation_segments (
    id bigint generated by default as identity primary key,
    run_id bigint references video_matrix_generation_runs(id) on delete cascade,
    asset_id bigint references video_matrix_generation_assets(id) on delete cascade,
    job_key text not null,
    sequence_number integer not null default 0,
    segment_index integer not null default 0,
    clip_id text not null default '',
    category text not null default '',
    source_path text not null default '',
    normalized_path text not null default '',
    start_time numeric not null default 0,
    duration numeric not null default 0,
    created_at bigint not null
);

drop policy if exists "brand viewers read video matrix generation runs" on video_matrix_generation_runs;
create policy "brand viewers read video matrix generation runs" on video_matrix_generation_runs for select to authenticated using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));
drop policy if exists "brand operators manage video matrix generation runs" on video_matrix_generation_runs;
create policy "brand operators manage video matrix generation runs" on video_matrix_generation_runs for all to authenticated using (brand_has_role(array['owner', 'admin', 'operator'])) with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read video matrix generation assets" on video_matrix_generation_assets;
create policy "brand viewers read video matrix generation assets" on video_matrix_generation_assets for select to authenticated using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));
drop policy if exists "brand operators manage video matrix generation assets" on video_matrix_generation_assets;
create policy "brand operators manage video matrix generation assets" on video_matrix_generation_assets for all to authenticated using (brand_has_role(array['owner', 'admin', 'operator'])) with check (brand_has_role(array['owner', 'admin', 'operator']));

drop policy if exists "brand viewers read video matrix generation segments" on video_matrix_generation_segments;
create policy "brand viewers read video matrix generation segments" on video_matrix_generation_segments for select to authenticated using (brand_has_role(array['owner', 'admin', 'operator', 'viewer']));
drop policy if exists "brand operators manage video matrix generation segments" on video_matrix_generation_segments;
create policy "brand operators manage video matrix generation segments" on video_matrix_generation_segments for all to authenticated using (brand_has_role(array['owner', 'admin', 'operator'])) with check (brand_has_role(array['owner', 'admin', 'operator']));
